# COGS 108 - Data Checkpoint

# Names

- Eric Chen
- Ziting Xiong
- Ziyan Sui (Flynn)
- Zhihan Li (Claire)

<a id='research_question'></a>
# Research Question

*Fill in your research question here*
#### Our Research 
What is the relationship between the concentration of charging stations in California and electric car purchase patterns in California, and how does this relationship vary across different regions and socio-economic factors, like gas prices, mean revenues of residents?

# Dataset(s)

*Fill in your dataset information here*

(Copy this information for each dataset)
- Dataset Name:
- Link to the dataset:
- Number of observations:

1-2 sentences describing each dataset. 

If you plan to use multiple datasets, add 1-2 sentences about how you plan to combine these datasets.

# Setup

In [4]:
## YOUR CODE HERE
import pandas as pd

# Data Cleaning

Describe your data cleaning steps here.

In [8]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION
# Vehicle_Population_ZIPCODE = pd.read_csv('https://raw.githubusercontent.com/EricChen0803/DATASET-TEMP/main/Datasets/Vehicle_Population/Vehicle_Population_ZIPCODE.csv')
# Vehicle_Population_ZIPCODE

Household = pd.read_csv('./Datasets/Household Census/Income by Country Name/ACSDP5Y2021.DP03-Data.csv')
# DP03_0062E median household (Claire)
Household

/var/folders/_g/k4209t910rzc87rqb5l_hv5w0000gn/T/ipykernel_49936/2668144342.py:6: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,254,255,256,257,262,263,264,265,270,271,272,273,278,279,280,281,286,287,288,289,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,354,355,356,357,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,550,553,578,581,586,587,602,605,610,611,618,619,650,653,674,675,730,731,750,753,846,849,902,905,926,929,946,949,954,957,958,961,962,965,982,985,1002,1005) have mixed types. Specify dtype option on import or set low_memory=False.
  Household = pd.read_csv('./Datasets/Household Census/Income by Country Name/ACSDP5Y2021.DP03-Data.csv')

,GEO_ID,NAME,DP03_0001E,DP03_0001M,DP03_0001MA,DP03_0001EA,DP03_0002E,DP03_0002EA,DP03_0002M,DP03_0002MA,...,DP03_0135PMA,DP03_0136PE,DP03_0136PM,DP03_0136PMA,DP03_0136PEA,DP03_0137PE,DP03_0137PM,DP03_0137PMA,DP03_0137PEA,Unnamed: 1098
0,Geography,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,...,Annotation of Percent Margin of Error!!PERCENT...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...,NaN
1,0500000US06001,"Alameda County, California",1367247,837,NaN,NaN,922490,NaN,4222,NaN,...,NaN,5.7,0.3,NaN,NaN,21.2,0.7,NaN,NaN,NaN
2,0500000US06003,"Alpine County, California",1084,187,NaN,NaN,575,NaN,145,NaN,...,NaN,8.5,5.8,NaN,NaN,32.3,15.0,NaN,NaN,NaN
3,0500000US06005,"Amador County, California",34850,147,NaN,NaN,16238,NaN,720,NaN,...,NaN,4.2,1.3,NaN,NaN,23.1,4.1,NaN,NaN,NaN
4,0500000US06007,"Butte County, California",178693,318,NaN,NaN,103769,NaN,1607,NaN,...,NaN,11.2,1.2,NaN,NaN,35.2,1.7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1862,860Z200US96148,ZCTA5 96148,616,233,NaN,NaN,387,NaN,179,NaN,...,NaN,0.0,7.3,NaN,NaN,0.0,19.6,NaN,NaN,NaN
1863,860Z200US96150,ZCTA5 96150,25473,779,NaN,NaN,17694,NaN,752,NaN,...,NaN,6.4,2.3,NaN,NaN,20.1,3.0,NaN,NaN,NaN
1864,860Z200US96155,ZCTA5 96155,0,13,NaN,NaN,0,NaN,13,NaN,...,**,-,**,**,-,-,**,**,-,NaN
1865,860Z200US96161,ZCTA5 96161,15447,405,NaN,NaN,10691,NaN,503,NaN,...,NaN,6.2,3.1,NaN,NaN,20.5,6.0,NaN,NaN,NaN
1866,860Z200US97635,ZCTA5 97635,152,101,NaN,NaN,56,NaN,51,NaN,...,NaN,26.0,34.0,NaN,NaN,0.0,100.0,NaN,NaN,NaN

In [ ]:
# California Energy Commission - Vehicle_population_county.csv (小熊）

In [ ]:
# INSERT EV_Chargers_Q2_2020.csv (ZIYAN)

In [5]:
# INSERT California_Gasoline_Prices.csv (Eric)
California_Gasoline_Prices = pd.read_csv('https://raw.githubusercontent.com/EricChen0803/DATASET-TEMP/main/Datasets/California_Gasoline_Prices.csv')
# Using apply function to change the month data to year
def keepYear(s):
    return int(s.split('-')[1])
California_Gasoline_Prices['Year'] = California_Gasoline_Prices.get('Month').apply(keepYear)
# Only keeping the data from 2020 to 2023
California_Gasoline_Prices = California_Gasoline_Prices[California_Gasoline_Prices.get("Year")>=20]
California_Gasoline_Prices = California_Gasoline_Prices[California_Gasoline_Prices.get("Year") <=23]
California_Gasoline_Prices['Year'] = California_Gasoline_Prices.get('Year')+2000
# Grouping to get the price per gallon for each year
California_Gasoline_Prices = California_Gasoline_Prices.get(['Year','California All Grades All Formulations Retail Gasoline Prices Dollars per Gallon']).groupby("Year").mean()
California_Gasoline_Prices

      California All Grades All Formulations Retail Gasoline Prices Dollars per Gallon
Year
2020                                           3.132917
2021                                           4.092917
2022                                           5.404750
2023                                           4.633000

# Updated Hypothesis

#### Our Hypothesis
We predict that the higher the concentration of charging stations, the higher the sales of electric vehicles, because of easier access to charging during trips and daily commutes, but the length of charging will still be a major problem to consider. The increasing gas prices in these two years caused by government policies and wars lead people more likely to buy EV, because electricity is significantly cheaper than fuels and over years it saves thousands of dollars. The higher the revenue of residents, the higher the sales, because EV are generally expensive compared to fuel cars right now and affordability is one important factor.